level-name=world
motd=USTC Campus PVP - 3/5 Points or Team Deathmatch - Java 26.2
server-ip=
server-port=25565
online-mode=true
max-players=12
gamemode=survival
force-gamemode=false
difficulty=normal
hardcore=false
pvp=true
spawn-protection=0
function-permission-level=2
op-permission-level=4
view-distance=8
simulation-distance=6
enable-rcon=false
enable-query=false
white-list=false
allow-flight=false
